##################################################################################################
# ############################ BY: NukkitX-Projects - depascaldc ############################### #
# ############################################################################################## #
# ############ Copyright (C) 2019 | depascaldc - Management | All Rights Reserved ############## #
# ################# WEBSITE: https://github.com/depascaldc/NukkitX-Projects##################### #
##################################################################################################

name: Better-Minecraft-DiscordSync
main: de.depascaldc.nukkitxproject.discordminecraftsync.Bot
version: "1.0.0"
api: ["1.0.8"]
author: depascaldc
description: Sync Discord and Minecraft
website: https://github.com/depascaldc/NukkitX-Projects
