##################################################################################################
# ############################ BY: NukkitX-Projects - depascaldc ############################### #
# ############################################################################################## #
# ############ Copyright (C) 2019 | depascaldc - Management | All Rights Reserved ############## #
# ################# WEBSITE: https://github.com/depascaldc/NukkitX-Projects##################### #
##################################################################################################

name: More-Essentials
main: de.depascaldc.nukkitxprojects.moreessentials.Essentials
version: "1.0.0"
api: ["1.0.8"]
author: depascaldc
description: Add more essentials to your server
website: https://github.com/depascaldc/NukkitX-Projects
